### ISSUE TITLE
[Question] 联网搜索无法使用

### ISSUE THREAD

**Issue by VectorZhao** [lobehub/chat-plugin-search-engine#3]
### 🧐 问题描述 | Proposed Solution

设置了serper 的 api key，但是一直没法使用。

<img width="1291" alt="image" src="https://github.com/lobehub/chat-plugin-search-engine/assets/16644993/c6f3529d-e329-48c3-a69e-46a466788c19">

**Comment by arvinxx** [comment]
你是不是用错服务了？

是这个 https://serpapi.com/

**Comment by VectorZhao** [comment]
> 你是不是用错服务了？
> 
> 是这个 https://serpapi.com/

额，真是用错服务了。谢谢。。。。。。。。。

**Comment by VectorZhao** [comment]
是不是，可以考虑增加google api 搜索功能：
```
## GOOGLE_API_KEY - Google API key (Default: None)
GOOGLE_API_KEY=xx
## GOOGLE_CUSTOM_SEARCH_ENGINE_ID - Google custom search engine ID (Default: None)
GOOGLE_CUSTOM_SEARCH_ENGINE_ID=xxx
```

**Comment by VectorZhao** [comment]
https://serpapi.com/
每月是100次，太少了

**Comment by arvinxx** [comment]
> 是不是，可以考虑增加google api 搜索功能：

你有相关 API 的开发文档么？我之前找没找到

**Comment by VectorZhao** [comment]
> > 是不是，可以考虑增加google api 搜索功能：
> 
> 你有相关 API 的开发文档么？我之前找没找到

应该是这里：
https://developers.google.com/custom-search/docs/tutorial/implementingsearchbox?hl=zh-cn

**Comment by arvinxx** [comment]
这个应该不是。![image](https://github.com/lobehub/chat-plugin-search-engine/assets/28616219/65d72cea-1c2c-4be8-9b10-b71fe3d54db5)看介绍是给网站添加搜索能力的

**Comment by VectorZhao** [comment]
https://developers.google.com/custom-search/v1/overview?hl=zh-cn

这里?
